// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protocol

/*
protoc --go_out=. message.proto
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatedUnit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedUnit) Reset()         { *m = CreatedUnit{} }
func (m *CreatedUnit) String() string { return proto.CompactTextString(m) }
func (*CreatedUnit) ProtoMessage()    {}
func (*CreatedUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{0}
}
func (m *CreatedUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedUnit.Unmarshal(m, b)
}
func (m *CreatedUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedUnit.Marshal(b, m, deterministic)
}
func (dst *CreatedUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedUnit.Merge(dst, src)
}
func (m *CreatedUnit) XXX_Size() int {
	return xxx_messageInfo_CreatedUnit.Size(m)
}
func (m *CreatedUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedUnit.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedUnit proto.InternalMessageInfo

// for test usage
type VoteRequest struct {
	ConflictUnit1        string   `protobuf:"bytes,1,opt,name=conflictUnit1,proto3" json:"conflictUnit1,omitempty"`
	ConfilictUnit2       string   `protobuf:"bytes,2,opt,name=confilictUnit2,proto3" json:"confilictUnit2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{1}
}
func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (dst *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(dst, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetConflictUnit1() string {
	if m != nil {
		return m.ConflictUnit1
	}
	return ""
}

func (m *VoteRequest) GetConfilictUnit2() string {
	if m != nil {
		return m.ConfilictUnit2
	}
	return ""
}

type VoteResponse struct {
	ConflictUnit1        string   `protobuf:"bytes,1,opt,name=conflictUnit1,proto3" json:"conflictUnit1,omitempty"`
	ConfilictUnit2       string   `protobuf:"bytes,2,opt,name=confilictUnit2,proto3" json:"confilictUnit2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{2}
}
func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (dst *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(dst, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetConflictUnit1() string {
	if m != nil {
		return m.ConflictUnit1
	}
	return ""
}

func (m *VoteResponse) GetConfilictUnit2() string {
	if m != nil {
		return m.ConfilictUnit2
	}
	return ""
}

type ReplicationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationRequest) Reset()         { *m = ReplicationRequest{} }
func (m *ReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicationRequest) ProtoMessage()    {}
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{3}
}
func (m *ReplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationRequest.Unmarshal(m, b)
}
func (m *ReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationRequest.Marshal(b, m, deterministic)
}
func (dst *ReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRequest.Merge(dst, src)
}
func (m *ReplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicationRequest.Size(m)
}
func (m *ReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRequest proto.InternalMessageInfo

type ReplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationResponse) Reset()         { *m = ReplicationResponse{} }
func (m *ReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationResponse) ProtoMessage()    {}
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{4}
}
func (m *ReplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationResponse.Unmarshal(m, b)
}
func (m *ReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationResponse.Marshal(b, m, deterministic)
}
func (dst *ReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationResponse.Merge(dst, src)
}
func (m *ReplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicationResponse.Size(m)
}
func (m *ReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationResponse proto.InternalMessageInfo

type HeartbeatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{5}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (dst *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(dst, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{6}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (dst *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(dst, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

// for test usage
type TestMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Cnt                  int32    `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e0f2b98b24da638f, []int{7}
}
func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (dst *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(dst, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TestMessage) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *TestMessage) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatedUnit)(nil), "protocol.CreatedUnit")
	proto.RegisterType((*VoteRequest)(nil), "protocol.VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "protocol.VoteResponse")
	proto.RegisterType((*ReplicationRequest)(nil), "protocol.ReplicationRequest")
	proto.RegisterType((*ReplicationResponse)(nil), "protocol.ReplicationResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "protocol.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "protocol.HeartbeatResponse")
	proto.RegisterType((*TestMessage)(nil), "protocol.TestMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_e0f2b98b24da638f) }

var fileDescriptor_message_e0f2b98b24da638f = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x31, 0x4b, 0xc7, 0x30,
	0x10, 0xc5, 0xf9, 0x5b, 0xac, 0x7a, 0xb5, 0x52, 0xaf, 0x2a, 0x19, 0x25, 0x88, 0x38, 0x09, 0xea,
	0x47, 0x70, 0x71, 0x71, 0x30, 0xa8, 0x8b, 0x2e, 0x69, 0x3c, 0x6b, 0x20, 0x26, 0xb5, 0x39, 0xbf,
	0xbf, 0x34, 0x4d, 0xc1, 0x3a, 0x3b, 0x25, 0xf7, 0xcb, 0xe3, 0xe5, 0xdd, 0x83, 0xfa, 0x93, 0x62,
	0xd4, 0x3d, 0x5d, 0x0e, 0x63, 0xe0, 0x80, 0xbb, 0xe9, 0x30, 0xc1, 0xc9, 0x1a, 0xaa, 0xdb, 0x91,
	0x34, 0xd3, 0xdb, 0x93, 0xb7, 0x2c, 0x5f, 0xa0, 0x7a, 0x0e, 0x4c, 0x8a, 0xbe, 0xbe, 0x29, 0x32,
	0x9e, 0x41, 0x6d, 0x82, 0x7f, 0x77, 0xd6, 0xf0, 0xf4, 0x7c, 0x25, 0x36, 0xa7, 0x9b, 0x8b, 0x3d,
	0xb5, 0x86, 0x78, 0x0e, 0x07, 0x13, 0xb0, 0x0b, 0xb9, 0x16, 0x5b, 0x49, 0xf6, 0x87, 0xca, 0x57,
	0xd8, 0x9f, 0xcd, 0xe3, 0x10, 0x7c, 0xa4, 0x7f, 0x76, 0x3f, 0x02, 0x54, 0x34, 0x38, 0x6b, 0x34,
	0xdb, 0xe0, 0xf3, 0x06, 0xf2, 0x18, 0xda, 0x15, 0x9d, 0xbf, 0x96, 0x08, 0xcd, 0x1d, 0xe9, 0x91,
	0x3b, 0xd2, 0xbc, 0x48, 0x5b, 0x38, 0xfc, 0xc5, 0xb2, 0xf0, 0x01, 0xaa, 0x47, 0x8a, 0x7c, 0x3f,
	0xd7, 0x87, 0x02, 0x76, 0x72, 0x93, 0x39, 0xec, 0x32, 0xe2, 0x09, 0x94, 0x8e, 0x7c, 0xcf, 0x1f,
	0x29, 0xde, 0xb6, 0xca, 0x13, 0x36, 0x50, 0x18, 0xcf, 0xa2, 0x48, 0x70, 0xba, 0x76, 0x65, 0x2a,
	0xff, 0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x6c, 0xc5, 0x67, 0x94, 0x01, 0x00, 0x00,
}
